### ISSUE TITLE
habitipy status doesn't work

### ISSUE THREAD

**Issue by kurokirasama** [ASMfreaK/habitipy#13]
I'm getting:

```
Traceback (most recent call last):
  File "/home/lgomez/.local/bin/habitipy", line 11, in <module>
    sys.exit(HabiticaCli())
  File "/home/lgomez/.local/lib/python3.6/site-packages/plumbum/cli/application.py", line 160, in __new__
    return cls.run()
  File "/home/lgomez/.local/lib/python3.6/site-packages/plumbum/cli/application.py", line 577, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/lgomez/.local/lib/python3.6/site-packages/plumbum/cli/application.py", line 572, in run
    retcode = inst.main(*tailargs)
  File "/home/lgomez/.local/lib/python3.6/site-packages/habitipy/cli.py", line 202, in main
    user['mount'] = content['mountInfo'][user['mount']]['text'] if user['mount'] else ''
KeyError: 'Velociraptor-White'

```

**Comment by ASMfreaK** [comment]
Hello!
You may have stale content
Please delete cache file:
 ```
rm ~/.config/habitipy/content.json
```
and try again. If this error persists, please do comment. I'll look closer into it.
I'll track stale content update in another isssue.

**Comment by kurokirasama** [comment]
cool, that worked!!!
I should probably open another ticket for this, but is there a way to filter todos?

**Comment by ASMfreaK** [comment]
Please do, I don't remember, if habitipy does any filtering.
