### ISSUE TITLE
Value v4 is missing from api

### ISSUE THREAD

**Issue by Stake2** [ASMfreaK/habitipy#22]
```
>>> from habitipy import Habitipy, load_conf,DEFAULT_CONF
>>> api = Habitipy(load_conf(DEFAULT_CONF))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\habitipy\api.py", line 192, in __init__
    _node = _node.into(part)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\habitipy\api.py", line 58, in into
    raise IndexError(_("Value {} is missing from api").format(val))  # NOQA: Q000
IndexError: Value v4 is missing from api
```
But v4 is the latest API version, how to change the module to use it?
I already tried changing this:
```current = current or ['api', "v4"]```

**Comment by ASMfreaK** [comment]
You would need to update `apidoc.txt`
