### ISSUE TITLE
Can't display dailies or todos

### ISSUE THREAD

**Issue by rawyak** [asmfreak/habitipy#24]
Hello everybody,
I installed Habitipy on my Linux computer (MX 21) and if i try to display my dailies or my todos I get this:

`$ habitipy todos
Traceback (most recent call last):
  File "/usr/local/bin/habitipy", line 8, in <module>
    sys.exit(HabiticaCli())
  File "/usr/local/lib/python3.9/dist-packages/plumbum/cli/application.py", line 177, in __new__
    return cls.run()
  File "/usr/local/lib/python3.9/dist-packages/plumbum/cli/application.py", line 639, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/usr/local/lib/python3.9/dist-packages/plumbum/cli/application.py", line 634, in run
    retcode = inst.main(*tailargs)
  File "/usr/local/lib/python3.9/dist-packages/habitipy/cli.py", line 314, in main
    res = i + prettify(self.domain_format(task))
  File "/usr/local/lib/python3.9/dist-packages/habitipy/util.py", line 102, in prettify
    string = emojize(string, use_aliases=True) if emojize else string
TypeError: emojize() got an unexpected keyword argument 'use_aliases'
`

This occurs regardless if in the output to be displayed there are emojis or not.
I installed it with "sudo pip install habitipy[emoji]".

Is there something I can do?

**Comment by ASMfreaK** [comment]
That library broke compatibility, sadly. I've fixed it now.

**Comment by hardaker** [comment]
close this issue?
